kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-postgres
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
